apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gptapp-backend
  name: gptapp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gptapp-server
  template:
    metadata:
      namespace: gptapp-backend
      labels:
        name: gptapp-server
    spec:
      containers:
        - name: gptapp-server
          image: gptapp.azurecr.io/pdfchat_backend/pdfchat_backend:kube4
          imagePullPolicy: Always
          command: 
            - "bash"
            - "-c"
            - "uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2"
          ports:
            - containerPort: 8000
              name: rest
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "2Gi"
              cpu: "1"
      imagePullSecrets:
        - name: azure-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---

apiVersion: v1
kind: Service
metadata:
  namespace: gptapp-backend
  name: gptapp-server
  
spec:
  selector:
    name: gptapp-server
  ports:
    - port: 80
      targetPort: rest
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: gptapp-backend
  name: gptapp-server-hpa
  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gptapp-server
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: "1Gi"
